server:
  port: 9099
  servlet:
    context-path: /

spring:
  #配置阿里巴巴数据源的四大件
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lws?useSSL=false&characterEncoding=utf8
    username: root
    password:
    # 连接池的配置信息
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
  mvc:
    #静态资源的访问路径
    static-path-pattern: /static/**
    #thymeleaf模板框架配置
    thymeleaf:
      #配置访问模版的路径前缀
      prefix: classpath:/templates/
      #配置访问模版的路径后缀
      suffix: .html
      #使用模版路径
      check-template-location: true
      #模版的编码为UTF-8
      encoding: UTF-8
      #模版的类型为text/templates.html
      servlet:
        content-type: text/html
      #使用html5相关标签
      mode: HTML5
      #不使用模版缓存
      cache: false

#配置mybatis
mybatis:
  #给实体对象取别名
  type-aliases-package: cn.com.djin.lws.entity
  #mapper.xml的访问路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #配置日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启懒加载
    lazy-loading-enabled: true
    #false 为按需加载
    aggressive-lazy-loading: false
    #开启MyBatis的二级缓存
    cache-enabled: true